name: Build Wii Homebrew

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    
    steps:
    - uses: actions/checkout@v4
        
    - name: Build Wii Homebrew
      run: make
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wii-homebrew
        path: |
          *.dol
          *.elf
          heheheha.dol