name: Build Wii Homebrew

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup devkitPro
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget -O devkitpro-pacman.deb https://github.com/devkitPro/pacman/releases/download/v1.0.2/devkitpro-pacman.amd64.deb
        sudo dpkg -i devkitpro-pacman.deb || sudo apt-get install -f -y
        sudo dkp-pacman -Sy
        sudo dkp-pacman -S wii-dev --noconfirm
        
    - name: Set environment variables
      run: |
        echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "DEVKITPPC=/opt/devkitpro/devkitPPC" >> $GITHUB_ENV
        echo "/opt/devkitpro/tools/bin" >> $GITHUB_PATH
        echo "/opt/devkitpro/devkitPPC/bin" >> $GITHUB_PATH
        
    - name: Build Wii Homebrew
      run: make
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wii-homebrew
        path: |
          *.dol
          *.elf
          heheheha.dol